### ISSUE TITLE
Unsupported version in docker-compose.yml

### ISSUE THREAD

**Issue by kerbe** [paschmann/changd#1]
I wanted to give changd a test drive, but I ran problems when trying to boot it up.

I get this error message when I do `docker-compose up`
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

My environment is WSL2 on Windows 10. 
Docker version 19.03.8, build afacb8b7f0
docker-compose version 1.25.4, build 8d51620a
Docker Desktop 4.4.3 (73365) is currently the newest version available.

**Comment by paschmann** [comment]
@kerbe - if you would like to test out the app in the mean time, I published a test instance here: [https://change.app](https://change.app)

**Comment by paschmann** [comment]
@kerbe - based on your 2nd issue, I believe this is an issue with your docker-compose version. Based on specs it shows that the v3.8 spec of the file was added in docker compose 1.25.5. (https://github.com/docker/compose/releases/tag/1.25.5)

I will see if there are any 3.8 specific params in the file and if not, downgrade the file version to 3.7 (or possibly lower).
