### ISSUE TITLE
Screenshot type error

### ISSUE THREAD

**Issue by PovilasID** [paschmann/changd#12]
I added a  line ` - ./data/screenshots:/app/screenshots` to docker compose in API to fix the folder access/crate issue but now I am getting type error...
```
Unable to get website screenshot: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Sharp
```

**Comment by PovilasID** [comment]
Which commit closes it?

**Comment by paschmann** [comment]
@PovilasID - Release 1.3.0 or the latest docker image should resolve this.
