### ISSUE TITLE
Amount of change

### ISSUE THREAD

**Issue by bradhawkins85** [paschmann/changd#14]
Would it be possible to use a percentage for the amount of change instead of Small, Medium, Major?
Also is it possible to show the percentage of change in the job history to allow easier adjustments of the threshold percentage?

My main goal is to track packages via various couriers and some are only tiny changes to the site such as "Onboard for delivery" becomes "Delivered in full" with most other elements not changing. Small changes does not alert for this.

**Comment by paschmann** [comment]
Hi @bradhawkins85 - that is a good suggestion. Did you test the XPath option? This feature allows you to track changes of specific HTML elements rather than the entire page.

**Comment by bradhawkins85** [comment]
Hi Paul,
I looked at the XPath option but could not figure out how to use it.
Any chance you could give me some tips on how to select the element to track? The only info I could find was for XML documents using XPath.

Awesome work so far on the project by they way, thank you.

**Comment by bradhawkins85** [comment]
Never mind, I figured out the below XPath syntax works.

For anyone else who needs it, example is based on this link https://msto.startrack.com.au/track-trace/?id=MVMZ00118468

XPath Element:
//*[contains(@id,'__c1_lblStatus')]
